### ISSUE TITLE
0.2.0 :  Cannot find module '../lib/index'

### ISSUE THREAD

**Issue by franckLdx** [fkrauthan/nss-run#1]
I've just download the 0.2.0 release and I can't run it:
```
Error: Cannot find module '../lib/index'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\fledoux\Documents\dev\gdk\cmd\node_modules\nss-run\bin\nss-run.js:8:21)
```

In node_modules\nss-run, there's no index directory:
![image](https://cloud.githubusercontent.com/assets/17727359/23357498/49da016c-fcde-11e6-98b9-c0377e15b7a3.png)

A 'npm run build' forgot before the publish ?

I've fixed this by getting the source code, running npm run build and copying the generated lib directory under node_modules/nss-run.

**Comment by fkrauthan** [comment]
Hmm weird. I will fix that ASAP. Not sure why the deployed npm version did not upload the lib folder correctly...

**Comment by fkrauthan** [comment]
I just uploaded `0.2.1` to NPM which includes the compiled version. I am very sorry about this issue.
